export const REDUCER = {
	SET_COUNT: "SET_COUNT",
	REQUESTING_COUNT: "REQUESTING_COUNT",
	REQUESTING_COUNT_CANCEL: "REQUESTING_COUNT",
	REQUESTING_COUNT_COMPLETE: "REQUESTING_COUNT",
	ADD_ERROR: "ADD_ERROR",
	CLEAR_ERROR: "CLEAR_ERROR"
};

export const NAVIGATION = {
	HOME : "HOME",
	COUNT: "COUNT",
	ABOUT : "ABOUT",
	PROFILE : "PROFILE",
	PERFORMANCE: "PERFORMANCE",
	QUESTIONS: "QUESTIONS"
};